project:
  type: website
website:
  title: "Kevin's Website"
  site-url: "https://klopezasc4.github.io/"
  repo-url: "https://github.com/KevinASC4/KevinASC4.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: project.qmd
        text: Past Projects
format:
  html:
    theme: journal
    toc: true