project:
  type: website
  output-dir: _site

website:
  title: "Kevin Lopez Sepulveda"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: nyt.qmd
        text: NYT Article Spotlight
      - href: syracuseUniversity.qmd
        text: Syracuse University
      - href: bostonUniversity.qmd
        text: Boston University