project:
  type: website

website:
  title: "KevinASC4.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        tezt: About
      - href: project.qmd
          text: project.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



