project:
  type: website
  output-dir: _site

site: 
  title: "Kevin's Quarto Site"
  base-url: /KevinASC4.github.io  # Ensure this matches your GitHub Pages URL
  navbar:
    left:
      - href: index.html  # Change .qmd to .html for navigation
        text: Home
      - href: about.html  # Change .qmd to .html for navigation
        text: About Me 
      - href: project.html  # Change .qmd to .html for navigation
        text: Past Projects