project:
  type: website
website:
  title: "Kevin's Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact
format:
  html:
    theme: journal
    toc: true