project:
  type: website
  output-dir: _site

site: 
  title: "Kevin's Quarto Site"
  base-url: /KevinASC4.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me 
      - href: project.qmd
        text: Past Projects