on:
  push:
<<<<<<< HEAD
    branches: 
      - main
=======
    branches:
      - main  # Correct branch trigger
>>>>>>> parent of 5450f11 (Manually deploy Quarto site)

name: quarto-publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Verify Quarto Installation
        run: quarto check

      - name: Render site
        run: |
          quarto render
          ls -l _site  # Debugging step to check if _site is generated

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Ensure this points to the correct directory
          publish_branch: gh-pages